// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkmpycttvbdffmxdmwck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrbXB5Y3R0dmJkZmZteGRtd2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTI5NDMsImV4cCI6MjA1ODk2ODk0M30.BMlfsIaimYeM8yDnoTia11K153q_HbB27_E8SIVn_hI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);